version: "3.8"

services:
  medusa-omer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/omerzirh/medusa-store
    container_name: medusa-omer
    networks:
      - medusa-network
    environment:
      NODE_ENV: production
      STORE_CORS: "https://store.omerzirh.com,https://autolier.pl"
      ADMIN_CORS: "https://store.omerzirh.com,https://admin.autolier.pl,http://localhost:8000"
      AUTH_CORS: "https://store.omerzirh.com,https://admin.autolier.pl"
      REDIS_URL: redis://:uOnV9g2MYYcQUHUuDyEKLcmNmOkPzqreMSz2zFjvDgWkIQUqRK8AwSxbAwppDLxD@5.161.64.194:6379
      JWT_SECRET: "super-secret"
      COOKIE_SECRET: "super-secret"
      DATABASE_URL: postgres://postgres:Omer1234@5.161.64.194:5432/medusa-medusa-store
      MEDUSA_WORKER_MODE: "shared"
    volumes:
      - medusa-uploads:/app/server/uploads
      - medusa-static:/app/server/static
    ports:
      - "9000:9000"
      - "7001:7001" 

volumes:
  medusa-uploads:
  medusa-static:

networks:
  medusa-network:
    driver: bridge
