version: "3.8"

services:
  medusa-omer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/omerzirh/medusa-store
    container_name: medusa-omer
    networks:
      - medusa-network
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      STORE_CORS: ${STORE_CORS}
      ADMIN_CORS: ${ADMIN_CORS}
      AUTH_CORS: ${AUTH_CORS}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      MEDUSA_WORKER_MODE: ${MEDUSA_WORKER_MODE:-shared}
    volumes:
      - medusa-uploads:/app/server/uploads
      - medusa-static:/app/server/static
    ports:
      - "9000:9000"
      - "7001:7001" 

volumes:
  medusa-uploads:
  medusa-static:

networks:
  medusa-network:
    driver: bridge