name: Build and Push Docker Image
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch; adjust as needed
  pull_request:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required to push to GitHub Container Registry
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.0  # Specify your project's pnpm version here
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Modify Dockerfile for pnpm version
        run: |
          # Replace the pnpm installation line with a specific version
          sed -i 's/npm install -g pnpm/npm install -g pnpm@8.6.0/g' Dockerfile
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64  # Ensure the image is built for the correct architecture
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: |
            PNPM_VERSION=8.6.0
            
      - name: Image info
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker images
